FORMAT: 1A
HOST: http://localhost:8565/mydevelopment/v1

# mydevelopment
TODO: Add Description

# Group Misc

## Talks 1 Attachments [/talks/1/attachments/]

### UPLOAD ATTACHMENT [POST]
TODO: Add Description
+ Attributes
    + file (string, required)


+ Request (application/json)
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 



### GET ATTACHMENTS [GET]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 




## Attachments 1 [/attachments/1]

### GET ATTACHMENT [GET]
TODO: Add Description

+ Request 
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 



### DELETE ATTACHMENTS [DELETE]
TODO: Add Description

+ Request 
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 



