FORMAT: 1A
HOST: http://example.com

# mydevelopment
TODO: Add Description

# Group Misc

## Mydevelopment V1 Talks 1 Attachments [/mydevelopment/v1/talks/1/attachments{?page_size}]

### httplocalhost8565mydevelopmentv1talks1attachmentspagesize1 [POST]
TODO: Add Description
+ Parameters
    + page_size (number, required)

        + Sample: 1
+ Attributes
    + file (string, required)


+ Request (application/json)
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 




## Mydevelopment V1 Attachments 1 [/mydevelopment/v1/attachments/1/]

### httplocalhost8565mydevelopmentv1attachments1 [GET]
TODO: Add Description

+ Request 
    + Headers

            X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJ1bGFuZyI6ImVuX1VTIiwidWlkIjoiMjUiLCJleHBpcmVzIjoxNDk4OTkwODY3LCJjbGFuZyI6ImVuX1VTIiwiY3JlYXRlZCI6MTQ5ODEyNjg2Nywicm9sZXMiOlsiQURNSU4iXSwibmFtZSI6InRzdGFyayIsInR0bCI6MzYwMCwiZGlkIjoxMjM0NSwiY2lkIjoiMjIyMSJ9.63JZlAbpWygcfADWJrqyy9gaBh8g5P6CS2hcDCUOnQc




+ Response 200 



