FORMAT: 1A
HOST: http://localhost/mydevelopment/v1/talks/1

# mydevelopment
TODO: Add Description

# Group Misc

## Attachments [/attachments{?page_size}]

### httplocalhost8565mydevelopmentv1talks1attachmentspagesize1 [POST]
TODO: Add Description
+ Parameters
    + page_size (number, required)

        + Sample: 1
+ Attributes
    + file (string, required)


+ Request (application/json)
    + Headers

            X-AUTH-TOKEN:




+ Response 200 



